name: npm
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout ðŸ”§
        uses: actions/checkout@v4.3.1
      - name: Install pnpm ðŸ”§
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.28.0
      - name: Setup Node ðŸ”§
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.21.1'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: build and Publish package on NPM ðŸ“¦
        run: |
           pnpm install --frozen-lockfile
           pnpm build
           npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}